"""ADUCA optimizer for block-separable monotone VI problems.

This implementation follows the adaptive delayed-update cyclic scheme from the
ADUCA draft.  It uses one-cycle-delayed partial operators, a GRAAL-like
extrapolated prox center, and the simplified locally adaptive step-size rule.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from .base import HistoryLogger, OptimizerResult


def _local_estimates(problem: Any, x_curr: np.ndarray, x_prev: np.ndarray, F_curr: np.ndarray, F_prev: np.ndarray, ftilde_curr: np.ndarray) -> tuple[float, float]:
    """Compute ADUCA's two local Lipschitz surrogates L_k and Lhat_k."""
    dx_norm = problem.primal_norm(x_curr - x_prev)
    if dx_norm <= 1e-15:
        return 0.0, 0.0
    Lk = problem.dual_norm(F_curr - F_prev) / dx_norm
    Lhat = problem.dual_norm(F_curr - ftilde_curr) / dx_norm
    return float(Lk), float(Lhat)


def _apply_stepsize_warmup(
    a_rule: float,
    a_prev: float,
    k: int,
    warmup_steps: int,
    warmup_change_factor: float,
) -> tuple[float, bool, float]:
    """Limit early multiplicative step changes, then release to ADUCA's rule.

    The first warm-up cycle allows at most ``warmup_change_factor`` change from
    the previous step. Later warm-up cycles relax the cap geometrically. After
    ``warmup_steps`` cycles, ``a_rule`` is returned unchanged.
    """
    if warmup_steps <= 0 or k > warmup_steps:
        return float(a_rule), False, 0.0

    change_limit = float(warmup_change_factor) ** max(int(k), 1)
    lower = float(a_prev) / change_limit
    upper = float(a_prev) * change_limit
    return float(min(max(float(a_rule), lower), upper)), True, change_limit


def run_aduca(
    problem: Any,
    x0: np.ndarray,
    num_iterations: int,
    beta: float = 0.8,
    gamma: float = 0.2,
    rho: float = 1.2,
    mu: float = 0.0,
    a0: float | None = None,
    log_every: int = 1,
    max_stepsize: float = 1e8,
    safeguard_primary: bool = False,
    safeguard_shrink: float = 0.5,
    safeguard_max_backtracks: int = 8,
    warmup_steps: int = 0,
    warmup_change_factor: float = 2.0,
) -> OptimizerResult:
    """Run ADUCA for ``num_iterations`` cycles/outer iterates.

    The first iterate is initialized by a full proximal step.  Subsequent
    iterates are generated by cyclic block updates using delayed partial
    operators, exactly the structure needed to stress-test local adaptivity on
    nonlinear BPR congestion maps.

    ``a0`` is retained only for compatibility with older experiment scripts.
    The initialization below always starts from a unit test step and computes
    its own backtracking start from the local ``L_1`` and ``Lhat_1`` estimates.
    """
    if not ((math.sqrt(5.0) - 1.0) / 2.0 < beta < 1.0):
        raise ValueError("ADUCA requires beta in ((sqrt(5)-1)/2, 1).")
    if not (0.0 < gamma < 1.0 - 1.0 / (beta * (1.0 + beta))):
        raise ValueError("ADUCA gamma is outside the simplified-rule admissible range.")
    if not (1.0 < rho < 1.0 / beta):
        raise ValueError("ADUCA requires rho in (1, 1/beta).")
    if safeguard_primary and not (0.0 < safeguard_shrink < 1.0):
        raise ValueError("safeguard_shrink must be in (0, 1).")
    safeguard_max_backtracks = max(int(safeguard_max_backtracks), 0)
    warmup_steps = max(int(warmup_steps), 0)
    if warmup_steps > 0 and not (float(warmup_change_factor) > 1.0):
        raise ValueError("warmup_change_factor must be greater than 1 when warmup_steps > 0.")

    rho0 = min(float(rho), float(beta) * (1.0 + float(beta)) * (1.0 - float(gamma)))
    eta = math.sqrt(float(gamma) * (1.0 + float(beta)) / (1.0 + float(beta) ** 2))
    tau = (3.0 * rho0**2 * (1.0 + float(rho) * float(beta))) / (
        2.0 * (float(rho) * float(beta)) ** 2 + 3.0 * rho0**2 * (1.0 + float(rho) * float(beta))
    )
    C_L = eta / (2.0 * math.sqrt(float(beta))) * math.sqrt(tau * float(rho) * float(beta)) / (
        math.sqrt(3.0) * math.sqrt(1.0 + float(rho) * float(beta))
    )
    C_Lhat = eta / (2.0 * math.sqrt(float(beta))) * math.sqrt((1.0 - tau) * float(rho) * float(beta)) / math.sqrt(2.0)

    x_init = problem.project_feasible(x0)
    logger = HistoryLogger("aduca", problem, log_every=log_every)
    logger.maybe_log(0, x_init, {"stepsize": 0.0, "Lk": 0.0, "Lhat": 0.0, "theta": 1.0}, force=True)

    if num_iterations <= 0:
        return OptimizerResult(method="aduca", x_final=x_init, history=logger.dataframe(), config={})

    ########### Initialization: test step, then backtracking to choose a_0 = a_{-1}. ###########
    F0 = problem.operator(x_init)
    logger.add_operator_evals(1)

    init_test_stepsize = 1.0
    x_test = problem.prox_full(x_init, F0, init_test_stepsize)
    F_test = problem.operator(x_test)
    ftilde_test = problem.delayed_cyclic_operator(x_test, x_init)
    logger.add_operator_evals(1 + problem.num_blocks)

    test_step_norm = problem.primal_norm(x_test - x_init)
    if test_step_norm <= 1e-15:
        init_L1_test = 0.0
        init_Lhat1 = 0.0
        a_start_raw = init_test_stepsize
    else:
        init_L1_test = float(problem.dual_norm(F_test - F0) / test_step_norm)
        init_Lhat1 = float(problem.dual_norm(F_test - ftilde_test) / test_step_norm)
        L1_candidate = C_L / init_L1_test if math.isfinite(init_L1_test) and init_L1_test > 1e-15 else float("inf")
        Lhat_candidate = C_Lhat / init_Lhat1 if math.isfinite(init_Lhat1) and init_Lhat1 > 1e-15 else float("inf")
        a_start_raw = min(L1_candidate, Lhat_candidate)
        if not math.isfinite(a_start_raw) or a_start_raw <= 0.0:
            a_start_raw = init_test_stepsize

    a_start = min(float(a_start_raw), float(max_stepsize))
    a_start = max(a_start, 1e-15)
    init_backtracks = 0
    while True:
        x_curr = problem.prox_full(x_init, F0, a_start)
        F_curr = problem.operator(x_curr)
        logger.add_operator_evals(1)
        step_norm = problem.primal_norm(x_curr - x_init)
        if step_norm <= 1e-15:
            init_L1 = 0.0
            break
        init_L1 = float(problem.dual_norm(F_curr - F0) / step_norm)
        if math.isfinite(init_L1) and init_L1 >= 0.0 and a_start * init_L1 <= 1.0:
            break
        if a_start <= np.finfo(float).tiny:
            break
        a_start *= 0.5
        init_backtracks += 1
    ftilde_prev = F0.copy()
    ftilde_curr = problem.delayed_cyclic_operator(x_curr, x_init)
    logger.add_operator_evals(problem.num_blocks)

    x_prev = x_init
    F_prev = F0
    v_prev = x_init.copy()  # v_0
    a_prevprev = a_start    # a_{-1}
    a_prev = a_start        # a_0
    omega_prev = 1.0        # omega_0
    theta = 1.0

    Lk, Lhat = _local_estimates(problem, x_curr, x_prev, F_curr, F_prev, ftilde_curr)
    logger.maybe_log(
        1,
        x_curr,
        {
            "stepsize": a_start,
            "Lk": Lk,
            "Lhat": Lhat,
            "theta": theta,
            "omega": omega_prev,
            "init_L1": init_L1,
            "init_L1_test": init_L1_test,
            "init_Lhat1": init_Lhat1,
            "init_a_start": a_start_raw,
            "init_test_stepsize": init_test_stepsize,
            "init_backtracks": init_backtracks,
            "safeguard_backtracks": 0,
        },
        force=True,
    )
    ######################################################################

    # Main loop: at iteration k, build u_{k+1} from u_k and u_{k-1}.
    for k in range(1, num_iterations):
        Lk, Lhat = _local_estimates(problem, x_curr, x_prev, F_curr, F_prev, ftilde_curr)
        growth_candidate = rho0 * a_prev
        smooth_candidate = float("inf")
        if Lk > 1e-15:
            smooth_candidate = min(smooth_candidate, C_L / Lk)
        if Lhat > 1e-15:
            smooth_candidate = min(smooth_candidate, C_Lhat / Lhat)
        if not math.isfinite(smooth_candidate):
            smooth_candidate = growth_candidate
        ratio = math.sqrt(max(a_prev / max(a_prevprev, 1e-300), 1e-300))
        a_rule = min(growth_candidate, smooth_candidate * ratio, float(max_stepsize))
        a_rule = max(a_rule, 1e-15)
        a, warmup_active, warmup_change_limit = _apply_stepsize_warmup(
            a_rule,
            a_prev,
            k,
            warmup_steps,
            warmup_change_factor,
        )
        a = max(a, 1e-15)

        current_gap = float(problem.wardrop_gap(x_curr, F_curr)[1]) if safeguard_primary else math.inf
        safeguard_backtracks = 0
        while True:
            x_next = x_curr.copy()
            v_center = np.empty_like(x_curr)
            ftilde_next = np.zeros_like(x_curr)
            partial_for_ftilde_next = x_curr.copy()
            flows_for_ftilde_next = problem.link_flows(partial_for_ftilde_next)

            for b, sl in enumerate(problem.block_slices):
                # Extrapolated delayed operator from Eq. (2) of the draft.
                fbar_b = ftilde_curr[sl] + (a_prev * omega_prev / a) * (F_prev[sl] - ftilde_prev[sl])
                # Prox-center v_k from Eq. (3).
                v_center[sl] = (1.0 - beta) * x_curr[sl] + beta * v_prev[sl]
                # Block prox update Eq. (4).
                x_next[sl] = problem.prox_block(v_center[sl], fbar_b, a, b)
                # Store Ftilde_{k+1,b} before writing the current block into the
                # partial vector, so current block remains from u_k as required.
                ftilde_next[sl] = problem.block_operator_from_flows(flows_for_ftilde_next, partial_for_ftilde_next[sl], b)
                logger.add_operator_evals(1)
                flows_for_ftilde_next = problem.apply_block_delta_to_flows(
                    flows_for_ftilde_next,
                    b,
                    x_next[sl] - partial_for_ftilde_next[sl],
                )
                partial_for_ftilde_next[sl] = x_next[sl]

            F_next = problem.operator(x_next)
            logger.add_operator_evals(1)
            if not safeguard_primary:
                break
            next_gap = float(problem.wardrop_gap(x_next, F_next)[1])
            if next_gap <= current_gap + max(1e-12, 1e-12 * abs(current_gap)) or safeguard_backtracks >= safeguard_max_backtracks:
                break
            a = max(float(a) * float(safeguard_shrink), 1e-15)
            safeguard_backtracks += 1
        omega = (1.0 + float(rho) * float(beta) * float(mu) * a) / (1.0 + float(mu) * a) if mu > 0 else 1.0
        theta = theta / max(omega_prev, 1e-15)

        L_next, Lhat_next = _local_estimates(problem, x_next, x_curr, F_next, F_curr, ftilde_next)
        logger.maybe_log(
            k + 1,
            x_next,
            {
                "stepsize": a,
                "stepsize_rule": a_rule,
                "warmup_active": int(warmup_active),
                "warmup_change_limit": warmup_change_limit,
                "Lk": L_next,
                "Lhat": Lhat_next,
                "theta": theta,
                "omega": omega,
                "rho0": rho0,
                "C_L": C_L,
                "C_Lhat": C_Lhat,
                "tau": tau,
                "safeguard_backtracks": safeguard_backtracks,
            },
        )

        # Shift all delayed quantities.
        x_prev, x_curr = x_curr, x_next
        F_prev, F_curr = F_curr, F_next
        ftilde_prev, ftilde_curr = ftilde_curr, ftilde_next
        v_prev = v_center
        a_prevprev, a_prev = a_prev, a
        omega_prev = omega

    logger.maybe_log(num_iterations, x_curr, {"stepsize": a_prev, "Lk": Lk, "Lhat": Lhat, "theta": theta}, force=True)
    return OptimizerResult(
        method="aduca",
        x_final=x_curr,
        history=logger.dataframe(),
        config={
            "beta": beta,
            "gamma": gamma,
            "rho": rho,
            "mu": mu,
            "a0": a_start,
            "init_a_start": a_start_raw,
            "init_test_stepsize": init_test_stepsize,
            "init_L1_test": init_L1_test,
            "init_Lhat1": init_Lhat1,
            "init_backtracks": int(init_backtracks),
            "rho0": rho0,
            "eta": eta,
            "tau": tau,
            "C_L": C_L,
            "C_Lhat": C_Lhat,
            "safeguard_primary": bool(safeguard_primary),
            "safeguard_shrink": float(safeguard_shrink),
            "safeguard_max_backtracks": int(safeguard_max_backtracks),
            "warmup_steps": int(warmup_steps),
            "warmup_change_factor": float(warmup_change_factor),
        },
    )
